// packages/client/src/routes/Register.tsx
import React from "react";
import { TextInput } from "carbon-components-react";

import { Form } from "../components";

const Register = () => {
  return (
    <Form
      title="Create an account"
      caption="Already have an account?"
      captionLink={{ link: "/login", text: "Log in" }}
    >
      <TextInput
        id="email"
        labelText="Email"
        placeholder="Enter your email..."
      />
      <TextInput.PasswordInput
        id="password"
        labelText="Password"
        placeholder="Enter your password..."
      />
      <TextInput.PasswordInput
        id="confirm-password"
        labelText="Confirm password"
        placeholder="Enter your password again..."
      />
    </Form>
  );
};

export default Register;

// packages/client-svelte-rollup/src/routes/Register.svelte
<script>
  import { TextInput, PasswordInput } from "carbon-components-svelte";
  import { Form } from "../components";
</script>

<Form
  title="Create an account"
  caption="Already have an account?"
  captionLink={{ text: 'Log in', link: '/login' }}>
  <div class="form-body-element">
    <TextInput light labelText="Email" placeholder="Enter your email..." />
  </div>
  <div class="form-body-element">
    <PasswordInput
      light
      labelText="Password"
      placeholder="Enter your password..." />
  </div>
  <div class="form-body-element">
    <PasswordInput
      light
      labelText="Confirm password"
      placeholder="Enter your password again..." />
  </div>
</Form>

<style>
  .form-body-element {
    margin-bottom: 16px;
  }
</style>
