// packages/client/src/components/Form.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";

  import { Button, Form, Tile } from "carbon-components-svelte";
  import ArrowRight16 from "carbon-icons-svelte/lib/ArrowRight16";

  export let title: string = "Title";
  export let caption: string = "Caption";
  export let captionLink: { text: string; link: string } | null = null;

  export let secondaryButtonText: string | null = null;
  export let primaryButtonText: string = "Continue";

  let dispatch = createEventDispatcher();

  function handleOnSubmit() {
    dispatch("submit");
  }
</script>

<div class="form">
  <Tile style="padding: 0">
    <Form on:submit={handleOnSubmit}>
      <div class="form-content">
        <div class="form-header">
          <h3>{title}</h3>
          <p>
            {caption}
            {#if captionLink}
              <a href={captionLink.link}>{captionLink.text}</a>
            {/if}
          </p>
        </div>

        <div class="form-body">
          <hr class="form-body-element" />
          <slot />
        </div>
      </div>

      <div class="form-footer">
        <Button
          style="min-width: 50%; min-height: 4rem; padding-top: 0"
          type="submit"
          icon={ArrowRight16}
          on:click={handleOnSubmit}>
          {primaryButtonText}
        </Button>
        {#if secondaryButtonText}
          <Button
            style="min-width: 50%; min-height: 4rem; padding-top: 0"
            kind="secondary">
            {secondaryButtonText}
          </Button>
        {/if}
      </div>
    </Form>
  </Tile>
</div>

<style>
  h3 {
    margin-bottom: 4px;
  }

  p {
    font-size: 0.875rem;
    color: var(--cds-text-02, #525252);
  }

  hr {
    border: none;
    border-top: 1px solid var(--cds-ui-03, #e0e0e0);
    margin-bottom: 16px;
  }

  .form {
    margin: 40px auto;
    max-width: 450px;
    padding: 0;
  }

  .form-content {
    padding: 16px 16px 40px 16px;
  }

  .form-header {
    margin-bottom: 48px;
  }

  .form-body-element {
    margin-bottom: 16px;
  }

  .form-footer {
    display: flex;
    flex-direction: row-reverse;
  }
</style>

// packages/client/src/components/Form/Form.tsx
import React from "react";
import { Add16 } from "@carbon/icons-react";
import { Button, Form as CarbonForm, Tile } from "carbon-components-react";

import "./Form.scss";

function handleOnSubmit(e: React.FormEvent<HTMLFormElement>) {
  e.preventDefault();
  console.log("Form.handleOnSubmit");
}

type FormProps = {
  title: string;
  caption: string;
  captionLink: { link: string; text: string } | null;
  submitButtonText: string;
  children: any[];
};

const Form = (props: FormProps) => {
  const { title, caption, captionLink, submitButtonText, children } = props;

  return (
    <div className="form">
      <Tile style={{ padding: 0 }}>
        <CarbonForm onSubmit={handleOnSubmit}>
          <div className="form-content">
            <div className="form-header">
              <h3>{title}</h3>
              <p>
                {caption}{" "}
                {captionLink && (
                  <a href={captionLink.link}>{captionLink.text}</a>
                )}
              </p>
            </div>

            <div className="form-body">
              <hr className="form-body-element" />
              {children.map(child => (
                <div className="form-body-element">{child}</div>
              ))}
            </div>
          </div>

          <div className="form-footer">
            <Button
              icon={Add16}
              style={{ minWidth: "50%", minHeight: "4rem", paddingTop: "0" }}
            >
              {submitButtonText}
            </Button>
          </div>
        </CarbonForm>
      </Tile>
    </div>
  );
};

export default Form;
