// packages/client/src/App.tsx
import React from "react";
import { BrowserRouter, Route, Switch } from "react-router-dom";
import { Content } from "carbon-components-react";

import { Header } from "./components";
import { Home, Login, NotFound, Register } from "./routes";
import "./App.scss";

const App = () => {
  return (
    <>
      <Header>
        <Content>
          <BrowserRouter>
            <Switch>
              <Route exact path="/" component={Home} />
              <Route path="/login" component={Login} />
              <Route path="/register" component={Register} />
              <Route component={NotFound} />
            </Switch>
          </BrowserRouter>
        </Content>
      </Header>
    </>
  );
};

export default App;

// packages/client/src/App.svelte
<script lang="ts">
  import router from "page";
  import { Content } from "carbon-components-svelte";

  import Header from "./components/Header.svelte";
  import Theme from "./components/Theme.svelte";

  import { About, Home, Login, NotFound, Register } from "./routes";

  let theme: "g10" = "g10";

  let page = undefined;
  let params = undefined;

  router("/", () => (page = Home));
  router("/about", () => (page = About));
  router("/login", () => (page = Login));
  router("/register", () => (page = Register));
  router("/*", () => (page = NotFound));

  router.start();
</script>

<Theme persist bind:theme>
  <Header />
  <Content>
    <svelte:component this={page} {params}/>
  </Content>
</Theme>
