// packages/client/src/routes/Register.svelte
<script>
  import {
    Button,
    Form,
    PasswordInput,
    TextInput,
  } from "carbon-components-svelte";

  import ArrowRight16 from "carbon-icons-svelte/lib/ArrowRight16";
</script>

<div class="form">
  <Form on:submit>
    <h3>Create an account</h3>
    <p>Already have an account? <a href="/login">Log in</a></p>

    <div class="form-content">
      <div class="form-element">
        <TextInput labelText="Email" placeholder="username@email.com" />
      </div>
      <div class="form-element">
        <PasswordInput labelText="Password" placeholder="••••••••" />
      </div>
      <div class="form-element">
        <PasswordInput labelText="Confirm password" placeholder="••••••••" />
      </div>
    </div>

    <div class="footer">
      <Button style="min-width: 150px" icon={ArrowRight16}>Continue</Button>
    </div>
  </Form>
</div>

<style>
  h3 {
    margin-bottom: 4px;
  }

  .form {
    margin: 40px auto;
    max-width: 450px;
    padding: 16px;
  }

  .form-content {
    margin: 48px auto;
  }

  .form-element {
    margin-bottom: 24px;
  }

  .footer {
    display: flex;
    flex-direction: row-reverse;
  }
</style>

// packages/client/src/routes/Register.tsx
import React from "react";
import { TextInput } from "carbon-components-react";

import { Form } from "../components";

const Register = () => {
  return (
    <Form
      title="Create an account"
      caption="Already have an account?"
      captionLink={{ link: "/login", text: "Log in" }}
    >
      <TextInput
        id="email"
        labelText="Email"
        placeholder="Enter your email..."
      />
      <TextInput.PasswordInput
        id="password"
        labelText="Password"
        placeholder="Enter your password..."
      />
      <TextInput.PasswordInput
        id="confirm-password"
        labelText="Confirm password"
        placeholder="Enter your password again..."
      />
    </Form>
  );
};

export default Register;
